"""empty message

Revision ID: afa4f9a76e7c
Revises: 08dfe895295b
Create Date: 2021-11-09 23:09:04.328552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa4f9a76e7c'
down_revision = '08dfe895295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('channels_name_key', 'channels', ['name'])
    # ### end Alembic commands ###
