"""empty message

Revision ID: 41dc546bb91f
Revises: 13991d6c55ba
Create Date: 2021-11-06 19:35:53.206635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dc546bb91f'
down_revision = '13991d6c55ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privateSubs', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('privateSubs', sa.Column('privateServerId', sa.Integer(), nullable=True))
    op.drop_constraint('privateSubs_id_fkey', 'privateSubs', type_='foreignkey')
    op.create_foreign_key(None, 'privateSubs', 'private_servers', ['privateServerId'], ['id'])
    op.create_foreign_key(None, 'privateSubs', 'users', ['userId'], ['id'])
    op.drop_column('privateSubs', 'id')
    op.add_column('subs', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('subs', sa.Column('serverId', sa.Integer(), nullable=True))
    op.drop_constraint('subs_id_fkey', 'subs', type_='foreignkey')
    op.create_foreign_key(None, 'subs', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'subs', 'servers', ['serverId'], ['id'])
    op.drop_column('subs', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subs', type_='foreignkey')
    op.drop_constraint(None, 'subs', type_='foreignkey')
    op.create_foreign_key('subs_id_fkey', 'subs', 'servers', ['id'], ['id'])
    op.drop_column('subs', 'serverId')
    op.drop_column('subs', 'userId')
    op.add_column('privateSubs', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'privateSubs', type_='foreignkey')
    op.drop_constraint(None, 'privateSubs', type_='foreignkey')
    op.create_foreign_key('privateSubs_id_fkey', 'privateSubs', 'private_servers', ['id'], ['id'])
    op.drop_column('privateSubs', 'privateServerId')
    op.drop_column('privateSubs', 'userId')
    # ### end Alembic commands ###
